version: '3.8'

services:
  user_registration_api:
    container_name: user_registration_api_container
    image: user_registration_api
    build: ./app
    ports:
      - "80:8000"
    env_file:
      - ${ENV}.env
    entrypoint: ./startup.sh
    depends_on:
      - db_mysql

  db_mysql:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    expose:
      - "3306"
    env_file:
      - ${ENV}.env
